Repository Riminder/hrflow-connectors, pull requests merged in 2022-01, with the labels that each got.

#5 Feature: add SmartRecruiters Push Profile
  src/hrflow_connectors/connectors/destinations/smartrecruiters/README.md
  src/hrflow_connectors/connectors/destinations/smartrecruiters/__init__.py
  src/hrflow_connectors/connectors/destinations/smartrecruiters/actions.py
  src/hrflow_connectors/connectors/destinations/smartrecruiters/spec.py
  tests/connectors/destinations/smartrecruiters/test_smart_candidate.py
Labels: enhancement

#19 Feature: Add Recruitee push profile action
  src/hrflow_connectors/connectors/destinations/recruitee/README.md
  src/hrflow_connectors/connectors/destinations/recruitee/__init__.py
  src/hrflow_connectors/connectors/destinations/recruitee/actions.py
  src/hrflow_connectors/connectors/destinations/recruitee/schemas.py
  src/hrflow_connectors/connectors/destinations/recruitee/spec.py
  tests/connectors/destinations/recruitee/__init__.py
  tests/connectors/destinations/recruitee/test_push_profile.py
Labels: enhancement

#21 Feature: Jobs Connector to Ceridian DayForce
  src/hrflow_connectors/connectors/boards/ceridian/README.md
  src/hrflow_connectors/connectors/boards/ceridian/__init__.py
  src/hrflow_connectors/connectors/boards/ceridian/actions.py
  src/hrflow_connectors/connectors/boards/ceridian/schemas.py
  src/hrflow_connectors/connectors/boards/ceridian/spec.py
  tests/connectors/boards/ceridian/__init__.py
  tests/connectors/boards/ceridian/test_pull_jobs.py
Labels: enhancement

#22 feat: add schemas models for connectors
  src/hrflow_connectors/connectors/boards/greenhouse/schemas.py
  src/hrflow_connectors/connectors/boards/smartrecruiters/schemas.py
  src/hrflow_connectors/connectors/boards/workable/schemas.py
  src/hrflow_connectors/connectors/destinations/smartrecruiters/schemas.py
Labels: enhancement

#27 Documentation 1.0.0
  README.md
  src/hrflow_connectors/connectors/ceridian/README.md
  src/hrflow_connectors/connectors/ceridian/connector.py
  src/hrflow_connectors/connectors/ceridian/docs/pull_jobs.md
  src/hrflow_connectors/connectors/crosstalent/README.md
  src/hrflow_connectors/connectors/crosstalent/connector.py
  src/hrflow_connectors/connectors/crosstalent/docs/pull_jobs.md
  src/hrflow_connectors/connectors/flatchr/README.md
  src/hrflow_connectors/connectors/flatchr/connector.py
  src/hrflow_connectors/connectors/flatchr/docs/push_profile.md
  src/hrflow_connectors/connectors/greenhouse/README.md
  src/hrflow_connectors/connectors/greenhouse/connector.py
  src/hrflow_connectors/connectors/greenhouse/docs/pull_jobs.md
  src/hrflow_connectors/connectors/greenhouse/docs/push_profile.md
  src/hrflow_connectors/connectors/monster/README.md
  src/hrflow_connectors/connectors/monster/connector.py
  src/hrflow_connectors/connectors/monster/docs/catch_profile.md
  src/hrflow_connectors/connectors/monster/docs/push_job.md
  src/hrflow_connectors/connectors/recruitee/README.md
  src/hrflow_connectors/connectors/recruitee/actions.py
  src/hrflow_connectors/connectors/recruitee/connector.py
  src/hrflow_connectors/connectors/recruitee/docs/pull_jobs.md
  src/hrflow_connectors/connectors/recruitee/docs/push_profile.md
  src/hrflow_connectors/connectors/sapsuccessfactors/README.md
  src/hrflow_connectors/connectors/sapsuccessfactors/connector.py
  src/hrflow_connectors/connectors/sapsuccessfactors/docs/pull_jobs.md
  src/hrflow_connectors/connectors/sapsuccessfactors/docs/push_profile.md
  src/hrflow_connectors/connectors/smartrecruiters/README.md
  src/hrflow_connectors/connectors/smartrecruiters/connector.py
  src/hrflow_connectors/connectors/smartrecruiters/docs/pull_jobs.md
  src/hrflow_connectors/connectors/smartrecruiters/docs/push_profile.md
  src/hrflow_connectors/connectors/taleez/README.md
  src/hrflow_connectors/connectors/taleez/connector.py
  src/hrflow_connectors/connectors/taleez/docs/pull_jobs.md
  src/hrflow_connectors/connectors/taleez/docs/push_profile.md
  src/hrflow_connectors/connectors/workable/README.md
  src/hrflow_connectors/connectors/workable/connector.py
  src/hrflow_connectors/connectors/workable/docs/pull_jobs.md
  src/hrflow_connectors/connectors/xml/README.md
  src/hrflow_connectors/connectors/xml/connector.py
Labels: documentation

#30 Feature/refacto action documentation
  src/hrflow_connectors/connectors/breezyhr/docs/pull_jobs.md
  src/hrflow_connectors/connectors/breezyhr/docs/push_profile.md
  src/hrflow_connectors/connectors/ceridian/docs/pull_jobs.md
  src/hrflow_connectors/connectors/crosstalent/docs/pull_jobs.md
  src/hrflow_connectors/connectors/crosstalent/docs/push_profile.md
  src/hrflow_connectors/connectors/flatchr/docs/push_profile.md
  src/hrflow_connectors/connectors/greenhouse/docs/pull_jobs.md
  src/hrflow_connectors/connectors/greenhouse/docs/push_profile.md
  src/hrflow_connectors/connectors/monster/docs/catch_profile.md
  src/hrflow_connectors/connectors/monster/docs/push_job.md
  src/hrflow_connectors/connectors/recruitee/docs/pull_jobs.md
  src/hrflow_connectors/connectors/recruitee/docs/push_profile.md
  src/hrflow_connectors/connectors/sapsuccessfactors/docs/pull_jobs.md
  src/hrflow_connectors/connectors/sapsuccessfactors/docs/push_profile.md
  src/hrflow_connectors/connectors/smartrecruiters/docs/pull_jobs.md
  src/hrflow_connectors/connectors/smartrecruiters/docs/push_profile.md
  src/hrflow_connectors/connectors/taleez/docs/pull_jobs.md
  src/hrflow_connectors/connectors/taleez/docs/push_profile.md
  src/hrflow_connectors/connectors/workable/docs/pull_jobs.md
  src/hrflow_connectors/connectors/xml/docs/pull_jobs.md
Labels: documentation

#29 Refacto: rename core class & SAP Connector & fix monster `PushJobAction`
  DOCUMENTATION.md
  README.md
  src/hrflow_connectors/connectors/breezyhr/actions.py
  src/hrflow_connectors/connectors/ceridian/actions.py
  src/hrflow_connectors/connectors/crosstalent/actions.py
  src/hrflow_connectors/connectors/flatchr/actions.py
  src/hrflow_connectors/connectors/greenhouse/actions.py
  src/hrflow_connectors/connectors/monster/actions.py
  src/hrflow_connectors/connectors/recruitee/actions.py
  src/hrflow_connectors/connectors/sapsuccessfactors/actions.py
  src/hrflow_connectors/connectors/smartrecruiters/actions.py
  src/hrflow_connectors/connectors/taleez/actions.py
  src/hrflow_connectors/connectors/workable/actions.py
  src/hrflow_connectors/connectors/xml/actions.py
  src/hrflow_connectors/core/action.py
  src/hrflow_connectors/utils/datetime_converter.py
  src/hrflow_connectors/utils/timedelta_converter.py
  tests/connectors/breezyhr/test_push_profile.py
  tests/connectors/crosstalent/test_push_profile.py
  tests/connectors/flatchr/test_push_profile.py
  tests/connectors/monster/test_catch_profile.py
  tests/connectors/monster/test_push_job.py
  tests/core/test_action.py
Labels: bug, enhancement

#33 Merge `dev` -> `master` : version 1.0.2
  CHANGELOG.md
  VERSION
  setup.cfg
Labels: bug, documentation

#34 Feature: add custom errors
  src/hrflow_connectors/connectors/breezyhr/actions.py
  src/hrflow_connectors/connectors/ceridian/actions.py
  src/hrflow_connectors/connectors/crosstalent/actions.py
  src/hrflow_connectors/connectors/flatchr/actions.py
  src/hrflow_connectors/connectors/greenhouse/actions.py
  src/hrflow_connectors/connectors/monster/actions.py
  src/hrflow_connectors/connectors/recruitee/actions.py
  src/hrflow_connectors/connectors/sapsuccessfactors/actions.py
  src/hrflow_connectors/connectors/smartrecruiters/actions.py
  src/hrflow_connectors/connectors/taleez/actions.py
  src/hrflow_connectors/connectors/workable/actions.py
  src/hrflow_connectors/connectors/xml/actions.py
  src/hrflow_connectors/core/action.py
  src/hrflow_connectors/core/auth.py
  src/hrflow_connectors/core/error.py
  tests/core/test_action.py
  tests/core/test_auth.py
  tests/core/test_error.py
Labels: enhancement

#36 Feature/bullhorn migration
  README.md
  src/hrflow_connectors/connectors/__init__.py
  src/hrflow_connectors/connectors/bullhorn/README.md
  src/hrflow_connectors/connectors/bullhorn/__init__.py
  src/hrflow_connectors/connectors/bullhorn/actions.py
  src/hrflow_connectors/connectors/bullhorn/connector.py
  src/hrflow_connectors/connectors/bullhorn/docs/push_profile.md
  src/hrflow_connectors/connectors/bullhorn/schemas.py
  src/hrflow_connectors/core/auth.py
  tests/connectors/bullhorn/__init__.py
  tests/connectors/bullhorn/test_push_profile.py
  tests/core/test_auth.py
Labels: enhancement

#42 Refacto: Change `credentials` to Config class
  .gitignore
  poetry.lock
  pyproject.toml
  src/hrflow_connectors/utils/config.py
  tests/conftest.py
  tests/connectors/breezyhr/test_pull_jobs.py
  tests/connectors/breezyhr/test_push_profile.py
  tests/connectors/bullhorn/test_push_profile.py
  tests/connectors/crosstalent/test_auth.py
  tests/connectors/crosstalent/test_pull_jobs.py
  tests/connectors/crosstalent/test_push_profile.py
  tests/connectors/flatchr/test_push_profile.py
  tests/connectors/greenhouse/test_push_profile.py
  tests/connectors/monster/test_catch_profile.py
  tests/connectors/monster/test_push_job.py
  tests/connectors/recruitee/test_push_profile.py
  tests/connectors/sapsuccessfactors/test_pull_jobs.py
  tests/connectors/sapsuccessfactors/test_push_profile.py
  tests/connectors/smartrecruiters/test_pull_jobs.py
  tests/connectors/smartrecruiters/test_push_profile.py
  tests/connectors/taleez/test_pull_jobs.py
  tests/connectors/taleez/test_push_profile.py
  tests/connectors/teamtailor/test_pull_jobs.py
  tests/connectors/teamtailor/test_push_profile.py
  tests/utils/test_adress_to_lat_long.py
  tests/utils/test_config.py
Labels: refacto

#44 Architecture/v 1.1.0
  DOCUMENTATION.md
  setup.cfg
  src/hrflow_connectors/connectors/breezyhr/connector.py
  src/hrflow_connectors/connectors/breezyhr/docs/pull_jobs.md
  src/hrflow_connectors/connectors/breezyhr/docs/push_profile.md
  src/hrflow_connectors/connectors/bullhorn/connector.py
  src/hrflow_connectors/connectors/bullhorn/docs/push_profile.md
  src/hrflow_connectors/connectors/ceridian/connector.py
  src/hrflow_connectors/connectors/ceridian/docs/pull_jobs.md
  src/hrflow_connectors/connectors/crosstalent/connector.py
  src/hrflow_connectors/connectors/crosstalent/docs/pull_jobs.md
  src/hrflow_connectors/connectors/crosstalent/docs/push_profile.md
  src/hrflow_connectors/connectors/flatchr/connector.py
  src/hrflow_connectors/connectors/flatchr/docs/push_profile.md
  src/hrflow_connectors/connectors/greenhouse/connector.py
  src/hrflow_connectors/connectors/greenhouse/docs/pull_jobs.md
  src/hrflow_connectors/connectors/greenhouse/docs/push_profile.md
  src/hrflow_connectors/connectors/monster/connector.py
  src/hrflow_connectors/connectors/monster/docs/catch_profile.md
  src/hrflow_connectors/connectors/recruitee/connector.py
  src/hrflow_connectors/connectors/recruitee/docs/pull_jobs.md
  src/hrflow_connectors/connectors/recruitee/docs/push_profile.md
  src/hrflow_connectors/connectors/sapsuccessfactors/connector.py
  src/hrflow_connectors/connectors/sapsuccessfactors/docs/pull_jobs.md
  src/hrflow_connectors/connectors/sapsuccessfactors/docs/push_profile.md
  src/hrflow_connectors/connectors/smartrecruiters/connector.py
  src/hrflow_connectors/connectors/smartrecruiters/docs/pull_jobs.md
  src/hrflow_connectors/connectors/smartrecruiters/docs/push_profile.md
  src/hrflow_connectors/connectors/taleez/connector.py
  src/hrflow_connectors/connectors/taleez/docs/pull_jobs.md
  src/hrflow_connectors/connectors/taleez/docs/push_profile.md
  src/hrflow_connectors/connectors/teamtailor/connector.py
  src/hrflow_connectors/connectors/teamtailor/docs/pull_jobs.md
  src/hrflow_connectors/connectors/teamtailor/docs/push_profile.md
  src/hrflow_connectors/connectors/workable/connector.py
  src/hrflow_connectors/connectors/workable/docs/pull_jobs.md
  src/hrflow_connectors/connectors/workable/docs/push_profile.md
  src/hrflow_connectors/connectors/xml/connector.py
  src/hrflow_connectors/connectors/xml/docs/pull_jobs.md
  src/hrflow_connectors/core/action.py
  src/hrflow_connectors/core/auth.py
  src/hrflow_connectors/core/connector.py
  src/hrflow_connectors/utils/adress_to_lat_long.py
  src/hrflow_connectors/utils/hrflow.py
  tests/connectors/workable/test_push_profile.py
  tests/core/test_action.py
  tests/core/test_connector.py
  tests/utils/test_event_parser.py
  tests/utils/test_job_and_board.py
  tests/utils/test_profile_and_source.py
Labels: documentation, enhancement

#46 typo: update README
  CONTRIBUTING.md
  README.md
Labels: documentation
